name: .NET Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    env:
      Version: 1.3.${{ github.run_number }}
      Solution_Path: ./src/GherXunit.sln  
      Project_Path: ./src/lib/GherXunit/GherXunit.csproj
      Package_Path: ./src/lib/GherXunit/**/*.
      NUGET_INDEX: https://api.nuget.org/v3/index.json      

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test ${{ env.Solution_Path }}

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build application
      run: dotnet build ${{ env.Solution_Path }} --no-restore --configuration ${{ matrix.configuration }}
      
    - name: Publish DLL Artifact
      if: github.ref == 'refs/heads/main'
      run: |
        dotnet pack ${{env.Project_Path}} --no-restore --configuration ${{ matrix.configuration }} -p:PackageVersion=${{ env.Version }}
        dotnet nuget push ${{env.Package_Path}}${{ env.Version }}.nupkg --api-key ${{ secrets.NUGET_KEY }} --source ${{ env.NUGET_INDEX }}